# Generated by Django 4.1.7 on 2023-03-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='even_date',
            new_name='event_date',
        ),
    ]
