# Generated by Django 4.1.7 on 2023-04-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cliente_groups_cliente_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('SOPORTE', 'Soporte'), ('TECNICO', 'Tecnico'), ('ADMIN', 'Admin')], max_length=7),
        ),
    ]
