# Generated by Django 4.1.7 on 2023-03-31 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_venue_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=7)),
                ('dni', models.CharField(max_length=9)),
                ('tlf', models.TextField()),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_incidencia', models.CharField(max_length=255, null=True)),
                ('desc_incidencia', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asignada', models.BooleanField(default=False)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='app.cliente')),
            ],
        ),
    ]
