# Generated by Django 4.1.7 on 2023-03-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cliente_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
