# Generated by Django 4.1.7 on 2023-04-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_incidencia_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MyClubUser',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
